name: 'Build jupyter python plot'
on:
  push:
    branches:
    - main
    - 'feat/**'
    paths:
    - 'src/jupyter-python-plot/**'
  workflow_dispatch:

env:
  TARGET_REGISTORY: registry.cn-hangzhou.aliyuncs.com
  TARGET_NAMESPACE: linuzb
  WORKLOAD_TYPE: jupyter-python-plot
  # Dockerfile: https://github.com/jupyter/docker-stacks/blob/main/images/pytorch-notebook/cuda11/Dockerfile
  # image: https://quay.io/repository/jupyter/pytorch-notebook?tab=tags
  BASE_REGISTORY: quay.io
  BASE_NAMESPACE: jupyter
  BASE_IMAGE: scipy-notebook
  BASE_TAG: python-3.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # git checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Use the git command to retrieve the current tag information and store it in the environment variable APP_VERSION.
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      # 登录 docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.TARGET_REGISTORY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build and push
        id: docker_build_
        uses: docker/build-push-action@v2
        with:
          push: true
          context: src/${{ env.WORKLOAD_TYPE }}
          # docker build arg
          build-args: |
            BASE_CONTAINER=${{ env.BASE_REGISTORY }}/${{ env.BASE_NAMESPACE }}/${{ env.BASE_IMAGE }}:${{ env.BASE_TAG }}
          tags: |
            ${{ env.TARGET_REGISTORY }}/${{ env.TARGET_NAMESPACE }}/${{ env.BASE_IMAGE }}:${{ env.BASE_TAG }}-${{ env.APP_VERSION }}
